services:
  - docker
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - 'node'
before_install:
  - docker pull rethinkdb:latest
  - docker run -d -p 28015:28015 rethinkdb
script:
  - npm test
  - npm run build

after_success:
jobs:
  include:
    - stage: npm release
      node_js: 'node'
      script:
        - npm run build
      deploy:
        provider: npm
        email: 'ron.zeidman@gmail.com'
        api_key: '$NPM_API_KEY'
        skip_cleanup: true
        on:
          tags: true
